### ISSUE TITLE
how can i fix it?

### ISSUE THREAD

**Issue by wintrue** [proviq/lusrmgr#10]
![image](https://user-images.githubusercontent.com/6380530/226323207-7c9a872c-b9bd-41e7-a2eb-73c4a109f398.png)
If UserGroup Is Nothing Then
            NoUserGroup = True
            Warnings.Add(New ADWarning("Unable to retrieve default user group", "The default user group (SID: S-1-5-32-545) could not be found on the target system. New users will not be assigned to any group."))
 End If

why UserGroup Is Nothing you check error is "The default user group (SID: S-1-5-32-545) could not be found on the target system. New users will not be assigned to any group."

**Comment by akruhler** [comment]
The default user group, which has the well-known SID S-1-5-32-545, should normally be present on the system. In case the system is lacking that group (which is not normal afaik), there is no default group assignment for new users.
