### ISSUE TITLE
Can not login to Guest Account default in Windows 10

### ISSUE THREAD

**Issue by huuson889** [proviq/lusrmgr#12]
I am using the Windows 10 Home Single Language version.

I have downloaded your app to create a Guest account for my friend using my laptop. When I opened your app, it already had the Guest account, and the Guest account also appeared on the switch account screen.

But when I clicked switch, nothing happened. I stayed on the same default account. What is going on? Please help me @akruhler 

![image](https://github.com/akruhler/AccountManagement/assets/91197035/7e67b07e-4a7d-44b9-814a-c647a24a0ca1)

![image](https://github.com/akruhler/AccountManagement/assets/91197035/ac7fe825-07d8-46c6-a4b9-d7026893d8c2)

**Comment by akruhler** [comment]
Did you try signing out first, then logging in to the guest account?
