### ISSUE TITLE
The file is actually malware

### ISSUE THREAD

**Issue by mxchist** [proviq/lusrmgr#2]
According with Virustotal [report](https://www.virustotal.com/gui/file/976d1b08533bd9b2352f631a6c5ff074e675457e773e4d4c185f28308df26b79), the lusrmgr.exe contains the Artemis!Trojan and W32.Malware.Gen. Downloading of this file makes a danger for your operation system.

**Comment by akruhler** [comment]
Unfortunately, it appears to be the case that few antivirus programs detect a false-positive when downloading the application. If your antivirus software blocks you from using it, you will either have to add an exception or disable the software temporarily. You may also compile the application from source if you like, using [Microsoft Visual Studio](https://visualstudio.com).
