### ISSUE TITLE
Specify hint when changing password

### ISSUE THREAD

**Issue by Anton-V-K** [proviq/lusrmgr#4]
**Is your feature request related to a problem? Please describe.**
Cannot specify password hint when changing/setting password for a user - thera is no such input in the dialog:
![image](https://user-images.githubusercontent.com/20116984/163691362-adb52797-e5db-4558-aaf1-d3b5a15dd407.png)

**Describe the solution you'd like**
An extra input in the Set password wher a hint can be specified.

**Describe alternatives you've considered**
Windows system allows a user to specify a hint when he/she is changing own password:
![image](https://user-images.githubusercontent.com/20116984/163707925-a1704445-6580-4e3b-834a-d74e16705cc6.png)

**Comment by akruhler** [comment]
Thanks for your request! The password hint unfortunately appears not to be a property accessible through the API which is used in the application to access the users and groups on the system. So whilst this would certainly be a useful feature to implement, it would require manipulation of the SAM database, which is not desired in the context of this application.
