### ISSUE TITLE
Project name confusion

### ISSUE THREAD

**Issue by 29039** [proviq/lusrmgr#5]
The Microsoft tool is called **lusrmgr** (lusrmgr.msc)

This tool is also called **lusrmgr** (lusrmgr.exe)

Thank you for making this tool, and lucky I found it - it is very useful, but it was not easy.

I think that it would be less confusing if this tool got its own name, which would also make it more searchable when looking for a Microsoft lusrmgr alternative, without thinking that this is the same tool as that one.

**Comment by akruhler** [comment]
Thanks for your request, I do agree with that. If you have any further suggestions to the project or the repository name, just let me know.

**Comment by 29039** [comment]
I'm not sure, control-userpasswords3 in reference to the other similar Microsoft tool **control userpasswords2**? I'm not very creative.

**Comment by krystian3w** [comment]
now repo use `/AccountManagement/` but not files from >= 2021.

MS saved olide links like: [`https://github.com/proviq/lusrmgr/issues/5`](https://github.com/proviq/lusrmgr/issues/5)

```yml
>>> https://github.com/proviq/lusrmgr/issues/5

> --------------------------------------------
> 301 Moved Permanently
> --------------------------------------------
Status:	301 Moved Permanently
Code:	301
Server:	GitHub.com
Date:	Sun, 29 May 2022 11:01:58 GMT
Content-Length:	0
Location:	https://github.com/proviq/AccountManagement/issues/5
server-timing:	nginx;desc="NGINX";dur=0.841322,glb;desc="GLB";dur=47.551253
x-pjax-url:	https://github.com/proviq/lusrmgr/issues/5
x-voltron-version:	ce5368f
Vary:	Accept-Encoding, Accept, X-Requested-With
X-Frame-Options:	DENY
Set-Cookie:	logged_in=no; Path=/; Domain=github.com; Expires=Mon, 29 May 2023 11:01:58 GMT; HttpOnly; Secure; SameSite=Lax
X-GitHub-Request-Id:	92A0:730C:734A22:957F6E:629352A6
connection:	close
```
