### ISSUE TITLE
Does not run under Windows 11

### ISSUE THREAD

**Issue by tdampier** [proviq/lusrmgr#6]
**Describe the bug**
Is this only for INTEL and not AMD processors?  As when I run it it gives me the dialog popup "This app can't run on your PC " 

**To Reproduce**
1. Download
2. Run .lusrmgr.exe 
Note: Running on AMD processor on Windows 11

**Expected behavior**

**Version**
Jut downloaded where do I find version?

Hardware:
Processor	AMD Ryzen 7 5700U with Radeon Graphics            1.80 GHz
Installed RAM	12.0 GB (9.85 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	Touch support with 10 touch points

**OS Edition**
Edition	Windows 11 Home
Version	21H2
Installed on	‎6/‎14/‎2022
OS build	22000.708
Experience	Windows Feature Experience Pack 1000.22000.708.0

**Additional context**

**Comment by akruhler** [comment]
The application should work regardless of your processor manufacturer, as long as it supports 32-bit applications, so both Intel and AMD processors should work fine. The only other system requirement is Windows Vista or later as well as .NET Framework version 4.6 or later. Does the error message give any additional information about the problem, or can you provide a screenshot?

**Comment by hatter1888** [comment]
i have the same problem. when i open the lusrmgr.exe it shows the name of my computer with (loading) next to it but it never actually loads.

**Comment by akruhler** [comment]
I tested the application using a virtual machine running Windows 11, it did run and function normally. Could you provide any information about your system, i.e. .NET Framework version or system specs? In addition, did you try running the application on a Windows 10 machine before?

**Comment by UsernameTooLon** [comment]
I'm also attempting to run this application on a Windows 11 computer and I'm running into the same issue as @hatter1888 - I just see the name of my computer with "(loading)" beside it, forever. 

I have .NET 4.8 (4.8.09037, specifically).

**Version**
1.6.3

**Hardware**
Processor: 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz   3.00 GHz
RAM: 32.0 GB (31.7 GB usable)
System type: 64-bit operating system, x64-based processor

**OS Edition**
Edition: Windows 11 Home
Version: 21H2
Installed on: 08/‎12/‎2021
OS build: 22000.978
Experience: Windows Feature Experience Pack 1000.22000.978.0

**Comment by Bill-Stewart** [comment]
Works for me on Windows 11 Home.

**Comment by itzrealashwin** [comment]
can you send the file on google drive? github dont respondig me.

**Comment by itzrealashwin** [comment]
> Works for me on Windows 11 Home.

plz dm me the file
