### ISSUE TITLE
[Does not run on Windows 10]  lusrmgr.exe v1.6.0-1.6.3 dont work on Windows 10

### ISSUE THREAD

**Issue by tnr20** [proviq/lusrmgr#9]
**Describe the bug**
My OS is Windows 10 . lusrmgr.exe v1.6.0  -  1.6.3  no one works

**To Reproduce**
1. Go to 'open lusrmgr'
2. Click on 'bottom left'

3. You can see: that program dont run and give 3 errors (see screenshot)  :  
![t](https://user-images.githubusercontent.com/49328456/213904858-0d2b4fad-a66c-4b21-9ea7-c12f4b7fee33.png)

**Expected behavior**
after i click on the program i must wait long time, and then after 1-2minutes i became only 3warnings bottom left . And then i cant do anything else

**Version**
The version of the application, begins with 1.6.0 until 1.6.3 

**OS Edition**
Windows 10 Home.

**Screenshots**
![nt](https://user-images.githubusercontent.com/49328456/213904554-649d6146-ebed-4836-a8a0-4e270deeb53b.png)

**Additional context**
**NOTE: But in version 1.5 and 1.5.1 i can run the program without any problems.** But the problem begins from [v1.6](https://github.com/proviq/AccountManagement/releases/tag/1.6) to [lusrmgr v1.6.3](https://github.com/proviq/AccountManagement/releases/tag/1.6.3) [Latest](https://github.com/proviq/AccountManagement/releases/latest)

Can You help me please? Thanks in Advance

**Comment by akruhler** [comment]
This looks like an error produced by the WinNT connection to your local machine.
Starting with version 1.6, the default connection address was changed to "localhost", rather than your machine Name, which was used prior to 1.6.
If you try to add your local PC via "Database -> Connect" (or just click the green arrow in the top bar), then use your PC name as host address (which is, according to your screenshot, "GAMER-PC"), then click connect, does it work?

**Comment by tnr20** [comment]
**Thanks for Reply Sir.
in the meantime i upgraded to Windows 11 but it still doesnt work.**



**i tried with lusrmgr.exe v1.6.0 but it still dont work. it gives again a error (Picture)**:



**First**:

![lusr](https://user-images.githubusercontent.com/49328456/217615539-07ef5ef6-9997-46e3-a5bc-914161b8885c.png)




**And than later if i try to connect, like you said Connect GAMER-PC, it says**:
![nnt](https://user-images.githubusercontent.com/49328456/217615777-a6fed11f-c46b-4062-91df-bea6e82f0a3b.png)


****and the last is this**:**

![grafik](https://user-images.githubusercontent.com/49328456/217616289-5adea0d1-e867-460f-b038-e8733de2b0d4.png)






****And another Error but its in German, my English is not good i cant translate it** :( **sorry . but it is already Codes in English**.**


![rt](https://user-images.githubusercontent.com/49328456/217618832-6450c477-4ce2-4bb9-ad65-0ad3e8730d65.png)






```

#Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei lusrmgr.ViewHandler_C.ViewChanged(View newView)
   bei lusrmgr.MainForm.MainTreeView_AfterSelect(Object sender, TreeViewEventArgs e)
   bei System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   bei System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   bei System.Windows.Forms.TreeView.WmNotify(Message& m)
   bei System.Windows.Forms.TreeView.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.9105.0 built by: NET481REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll.
----------------------------------------
lusrmgr
    Assembly-Version: 1.6.0.0.
    Win32-Version: 1.6.0.0.
    CodeBase: file:///C:/Users/taner/Desktop/lusrmgr.exe.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.9130.0 built by: NET481REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.9075.0 built by: NET481REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.9032.0 built by: NET481REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
Microsoft.VisualBasic
    Assembly-Version: 10.0.0.0.
    Win32-Version: 14.8.9032.0 built by: NET481REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.9130.0 built by: NET481REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.9032.0 built by: NET481REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.9032.0 built by: NET481REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.9032.0 built by: NET481REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------
System.DirectoryServices
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.9032.0 built by: NET481REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.DirectoryServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.DirectoryServices.dll.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.9032.0 built by: NET481REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------

************** JIT-Debuggen **************
Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
Konfigurationsdatei der Anwendung oder des Computers
(machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.

Zum Beispiel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wenn das JIT-Debuggen aktiviert ist, werden alle nicht behandelten
Ausnahmen an den JIT-Debugger gesendet, der auf dem
Computer registriert ist, und nicht in diesem Dialogfeld behandelt.

```





Can you help me, or other Users? Thank you very much Sir

**Comment by akruhler** [comment]
I suggest you investigate regarding the system error you get upon launching the application.
As this app uses system functions and system services, the error is most probably in your system, as the error message suggest.
https://www.windows-faq.de/2021/09/04/fehler-1722-der-rpc-server-ist-nicht-verfuegbar/
Following this guide, is the RPC service running on your machine?

**Comment by tnr20** [comment]
the RPC-Server is on. without RPC Server , the system would crashed or i cant even login to internet...
The problem is somewhere other... Maybe another Error, i dunno. But previously i had never problem.
But with [lusrmgr v1.5](https://github.com/proviq/AccountManagement/releases/tag/1.5) and [lusrmgr v1.5.1](https://github.com/proviq/AccountManagement/releases/tag/1.5.1) i have not problem.

**Comment by akruhler** [comment]
Does the version 1.5.1 work flawlessly, i.e. you can use it normally and see all users and the default groups?
If it does, then the only major change to loading the users and groups in the 1.6 was to introduce an LSA lookup, to retrieve all built-in security principals. You may try to remove that LSA lookup in the 1.6.3 and see if it works then. To do that, remove lines 93-104 in the file ActiveDirectory.vb and replace these lines with this one: `BuiltInPrincipals = New List(Of BuiltInPrincipal)(0)`
If you have not worked with the code yet, you simply download the code as well as [Visual Studio 2022 from Microsoft](https://visualstudio.microsoft.com), where you choose to install the .NET Desktop tools.
If you wish not to work with the code, I can also share a binary with that change: [lusrmgr_1.6.3_noLSA.zip](https://github.com/proviq/AccountManagement/files/10715679/lusrmgr_1.6.3_noLSA.zip)

**Comment by dailytabs** [comment]
FYI: I had the same issue with latest 1.6.x on Windows 11. DCOM is running. Same 3 errors and same host error when using machine name. Latest 1.5.x worked for my need.

**Comment by akruhler** [comment]
Thanks for sharing. I was not able to reproduce the error on any test machine, it seems to appear only rarely. Maybe you could share some information about your system (for example what country, which OS version and edition, maybe anything else you think might be differently configured on your PC?)
